[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/clinvar_MT.vcf.gz"
fields = ["ALLELEID","CLNDN","CLNREVSTAT","CLNSIG"]
ops=["self","self","self","self"]
names=["CVid","CVdn","CVrev","CVsig"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/MITOTIP_scores.tsv.gz"
columns = [4,5]
ops=["self","self"]
names=["MTs","MTq"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/HMTDB_var_pa_tot.tsv.gz"
columns = [3]
ops=["self"]
names=["HMTDBp"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/HMTDB_var_tot.tsv.gz"
columns = [3]
ops=["self"]
names=["HMTDBh"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/MITOMAP_disease.vcf.gz"
fields = ["AC","AF","homoplasmy","heteroplasmy","Disease","DiseaseStatus","HGFL"]
ops=["self","self","self","self","self","self","self"]
names=["MMac","MMPaf","MMPhom","MMhtz","MMd","MMs","MMhg"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/MITOMAP_polymorphisms.vcf.gz"
fields = ["AC","AF","HGFL"]
ops=["self","self","self"]
names=["MMac","MMaf","MMhg"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/MitImpact_db.vcf.gz"
fields = ["P2","SIFT","FATW","FAT","PROV","MUTASS","EFINSP","EFINHD","CADD","PANTHER","PHDSNP","SNAP","METASNP","CAROL","CONDEL","COVEC","MTOOLBOX","APOGEE","MTASTER","MTCLASS"]
ops=["self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self"]
names=["P2","SIFT","FATW","FAT","PROV","MUTASS","EFINSP","EFINHD","CADD","PANTHER","PHDSNP","SNAP","METASNP","CAROL","CONDEL","COVEC","MTOOLBOX","APOGEE","MTASTER","MTCLASS"]


[[annotation]]
file="/home/dooguy/Dev_prog/Dev_KerMit/data/chrM_HP.bed"
columns = [4]
ops=["self"]
names=["HP"]
